#cloud-config
package_update: true
packages:
  - python3
  - python3-pip

users:
  - name: mlsysops
    shell: /bin/bash
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${public_key}

disable_root: true
ssh_pwauth: false
